In [1]:
# Step 1: Import required libraries
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

# Step 2: Load dataset (Iris dataset)
iris = datasets.load_iris()
X = iris.data      # Features
y = iris.target    # Target

# Step 3: Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0
)

# Step 4: Create Naïve Bayes model
model = GaussianNB()

# Step 5: Train the model
model.fit(X_train, y_train)

# Step 6: Make predictions
y_pred = model.predict(X_test)

# Step 7: Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Step 8: Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

Confusion Matrix:
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]

Accuracy: 1.0
